esphome:
  name: dryer_current
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: "SALNET"
  password: !secret network_psswd
  manual_ip:
    static_ip: 192.168.1.83
    gateway: !secret router_host
    subnet: 255.255.255.0

# Enable logging
logger:

api:

ota:

sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Dryer Current"
    unit_of_measurement: "A"
    icon: "mdi:flash-circle"
    id: dryer_current
    update_interval: 60s
    filters:
      - filter_out: nan
      - calibrate_linear:
          - 0.0 -> 0.0
          - 0.058 -> 7.00
              
  - platform: adc
    pin: A0
    id: adc_sensor

binary_sensor:
  - platform: template
    name: "Dryer Status"
    filters:
      - delayed_on: 240s
      - delayed_off: 240s
    lambda: |-
      if (isnan(id(dryer_current).state)) {
        return {};
      } else if (id(dryer_current).state > 3) {
        return true;
      } else {
        return false;
      }